[package]
name = "Decoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
rocket_codegen = "0.4.4"
rocket_contrib = "0.4.4"
serde_json = "*"
serde = { version = "1.0.104", features = ["derive"] }
